### ISSUE TITLE
limiting the time of reproducing a recorded session by bbb per user

### ISSUE THREAD

**Issue by MCalderonT** [kabalin/moodle-media_jwplayer#3]
Hello,
We are having problems with our students. They are sharing their user and password in Moodle to watch the recorded sessions by BigBlueButton. Could your player limit the time of reproducing a recorded session per user?

Thanks in advance

**Comment by kabalin** [comment]
Hello @MCalderonT. This repository is containing a media player plugin, which can play any supported media file without any limits (as long as you have a license). I have no idea how BigBlueButton works and wheter its media content can be played by third party player, sorry.
