### ISSUE TITLE
Multi audio track support with M3U8 manifest

### ISSUE THREAD

**Issue by TopSolid-DaA** [kabalin/moodle-media_jwplayer#6]
Hi,
For multi audio tracks activation, I need to attach a m3u8 file to the video file, just like subtitles, chapters etc.
Check here:
https://support.jwplayer.com/articles/multiple-audio-renditions-reference

How can I do that with the plugin in Moodle, even manually? Is it possible to add a tab in the media dialog box?

Thanks for help

**Comment by kabalin** [comment]
Hello @TopSolid, sorry for the delay in responding, I overlooked the notification. That is not possible at the moment, and in fact that functionality requires changes in Moodle, not at the plugin. Feel free to propose at Moodle tracker.

**Comment by kabalin** [comment]
Just looking in more details at this issue. You can't add m3u8 as additional file (no interface for specify multiple sources, although you can try to do that manually, player will not be using them together, but will pick only one), but if your m3u8 manifest contains all audio tracks and includes original video, it is supposed to work the way you need I believe (there will be an interface to switch audio track in the player of selected version supports it).

**Comment by TopSolid-DaA** [comment]
@kabalin Thanks kabalin. When you mention to do that manually, you meean modifying the code directly using the editor? Do you have examples of code that could help?

**Comment by kabalin** [comment]
> @kabalin Thanks kabalin. When you mention to do that manually, you meean modifying the code directly using the editor? Do you have examples of code that could help?

Something like this:
```
<video width="800">
  <source src="/media/cc0-videos/flower.m3u8" type="application/x-mpegURL" />
  <source src="/media/cc0-videos/flower.mp4" type="video/mp4" />
</video>
```
